[package]
name = "LD43"
version = "0.1.0"
authors = ["Paul Tilley <t1000.pixlark@gmail.com>"]

[dependencies]
lazy_static = "1.2.0"
rand = "0.6.1"

[dependencies.sdl2]
version = "0.31.0"
default-features = false
features = ["image", "ttf"]
