make:
	gcc -g main.c stretchy_buffer.c -lm -lSDL2 -o game

windows:
	gcc -g main.c stretchy_buffer.c -lm -lSDL2 -o game \
		-I"G:\.minlib\SDL2-2.0.7\x86_64-w64-mingw32\include" \
		-L"G:\.minlib\SDL2-2.0.7\x86_64-w64-mingw32\lib"
